name: data

on:
  push:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    env:
        RPC_URL: ${{ secrets.RPC_URL }}
        RPC_PASSWORD: ${{ secrets.RPC_PASSWORD }}
    permissions:
        contents: write
    steps:
      - uses: actions/checkout@v4
      - run: npm run data
      - uses: stefanzweifel/git-auto-commit-action@v5
